fixed artifacts was not stored when dome error happend.

diff --git a/.github/workflows/firefoxtest.yml b/.github/workflows/firefoxtest.yml
--- a/.github/workflows/firefoxtest.yml
+++ b/.github/workflows/firefoxtest.yml
@@ -71,12 +71,16 @@ jobs:
         ruby ./travisci/webserver.rb 2>log/web.log &
         sleep 3 # give some software a moment to start
     - name: Run tests
+      continue-on-error: true # とにかくログを保存するとこまで行きたい
+      id: usecase
       run: |
         chmod ugo+x ./travisci/runontravis.sh
         ./travisci/runontravis.sh ${{ matrix.kifu }}
       env:
         DISPLAY: :99
     - name: Byouyomi
+      continue-on-error: true # とにかくログを保存するとこまで行きたい
+      id: byouyomi
       run: bundle exec ruby ./observer/byouyomichan.rb 10
     - name: save taikyoku logs
       uses: actions/upload-artifact@v2
@@ -87,3 +91,13 @@ jobs:
           db
           log
           taikyoku
+    - name: check error u
+      if: ${{ steps.usecase.outcome }} == 'failure'
+      run: |
+        echo ${{ steps.usecase.outcome }} == 'failure'
+        exit 1
+    - name: check error b
+      if: ${{ steps.byouyomi.outcome }} == 'failure'
+      run: |
+        echo ${{ steps.byouyomi.outcome }} == 'failure'
+        exit 1
